env: standard
runtime: nodejs18
service: cms-strapi
runtime_config:
  operating_system: ubuntu22
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""
env_variables:
  # MY_ENV_VAR1: $MY_ENV_VAR1
  # MY_ENV_VAR2: $MY_ENV_VAR2
