env: standard
runtime: nodejs18
service: cms-strapi-develop
runtime_config:
  operating_system: ubuntu22
basic_scaling:
  max_instances: 1
  idle_timeout: 10m
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""
env_variables:
  HOST: $HOST
  APP_KEYS: $APP_KEYS
  API_TOKEN_SALT: $API_TOKEN_SALT
  ADMIN_JWT_SECRET: $ADMIN_JWT_SECRET
  TRANSFER_TOKEN_SALT: $TRANSFER_TOKEN_SALT
  DATABASE_CLIENT: $DATABASE_CLIENT
  DATABASE_HOST: $DATABASE_HOST
  DATABASE_PORT: $DATABASE_PORT
  DATABASE_NAME: $DATABASE_NAME
  DATABASE_USERNAME: $DATABASE_USERNAME
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  JWT_SECRET: $JWT_SECRET
  IMPUGNY_TOKEN_MELI: $IMPUGNY_TOKEN_MELI
